### ISSUE TITLE
help!!!

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [SilasRodrigues19/NLW-IA#5]
congratulations dude...but please can you check again your amazing project?dont work!!!

**Comment by SilasRodrigues19** [comment]
Hey @KENPOKASMMA1982 

Unfortunately the project actually broke, I enabled FFmpeg logs and it seems that now there are problems converting from `.mp4` to `.mp3`

I'm not familiar with FFMpeg and I haven't yet been able to interpret the logs to come up with possible solutions.

![image](https://github.com/SilasRodrigues19/NLW-IA/assets/47532703/38b4885e-55c0-4f9d-9a8c-3c75f0c43bcf)

**Comment by KENPOKASMMA1982** [comment]
hola amigo desde Grecia!en serio?que lastima Silas..y crees que puedas funcionarlo?es posible?

**Comment by SilasRodrigues19** [comment]
Fala @KENPOKASMMA1982 

Vou escrever em Português mesmo porque vou conseguir explicar melhor no meu idioma nativo. Como você escreveu em Espanhol imagino que você entenderá ou poderá traduzir também com o Google Translate.

O projeto já está funcionando novamente, porém tem algumas pequenas restrições devido ao backend estar hospedado de maneira gratuita no [Render](https://render.com/)

Primeiro precisa esperar o endpoint `/prompts` finalizar a requisição para aparecer a listagem dos Prompts

![image](https://github.com/SilasRodrigues19/NLW-IA/assets/47532703/faac262b-2001-4c9e-a0da-ca6d8f91097f)

Após selecionar o vídeo desejado e clicar no botão `Carregar vídeo`, será feita uma requisição `POST` para o endpoint `/videos` que salvara o vídeo no formado `.mp3` na base de dados.

Em seguida o endpoint `/transcription` é chamado para poder gerar a transcrição desse `.mp3` que foi salvo. Se tudo ocorrer bem o botão estará em uma cor de esmeralda com o texto `Finalizado!`

E por fim, ao clicar no botão `Executar` é onde acontece a chamada para o endpoint `/complete` que passa os dados para que a IA gere o texto. No print à seguir, como você pode ver na aba `Network` do meu console mostra que os 4 endpoints retornaram status 200, o que significa que tudo ocorreu bem.

![image](https://github.com/SilasRodrigues19/NLW-IA/assets/47532703/1bc1e64c-50ca-42f9-8a1d-535602612c88)

Se não funcionar pode ser devido a alguma instabilidade da plataforma onde está hospedado o backend, infelizmente precisa checar na aba `Network` se todas as requisições retornam o status 200 e o tempo de cada requisição pode levar mais tempo dependendo de diversos fatores, como por exemplo a velocidade de conexão com a internet ou a instabilidade dos servidores da Render.

**Comment by SilasRodrigues19** [comment]
> Fala @KENPOKASMMA1982
> 
> Vou escrever em Português mesmo porque vou conseguir explicar melhor no meu idioma nativo. Como você escreveu em Espanhol imagino que você entenderá ou poderá traduzir também com o Google Translate.
> 
> O projeto já está funcionando novamente, porém tem algumas pequenas restrições devido ao backend estar hospedado de maneira gratuita no [Render](https://render.com/)
> 
> Primeiro precisa esperar o endpoint `/prompts` finalizar a requisição para aparecer a listagem dos Prompts
> 
> ![image](https://user-images.githubusercontent.com/47532703/270064284-faac262b-2001-4c9e-a0da-ca6d8f91097f.png)
> 
> Após selecionar o vídeo desejado e clicar no botão `Carregar vídeo`, será feita uma requisição `POST` para o endpoint `/videos` que salvara o vídeo no formado `.mp3` na base de dados.
> 
> Em seguida o endpoint `/transcription` é chamado para poder gerar a transcrição desse `.mp3` que foi salvo. Se tudo ocorrer bem o botão estará em uma cor de esmeralda com o texto `Finalizado!`
> 
> E por fim, ao clicar no botão `Executar` é onde acontece a chamada para o endpoint `/complete` que passa os dados para que a IA gere o texto. No print à seguir, como você pode ver na aba `Network` do meu console mostra que os 4 endpoints retornaram status 200, o que significa que tudo ocorreu bem.
> 
> ![image](https://user-images.githubusercontent.com/47532703/270065444-1bc1e64c-50ca-42f9-8a1d-535602612c88.png)
> 
> Se não funcionar pode ser devido a alguma instabilidade da plataforma onde está hospedado o backend, infelizmente precisa checar na aba `Network` se todas as requisições retornam o status 200 e o tempo de cada requisição pode levar mais tempo dependendo de diversos fatores, como por exemplo a velocidade de conexão com a internet ou a instabilidade dos servidores da Render.

Vou fechar a ISSUE porque não se trata de um bug de fato, são apenas as limitações devido a hospedagem em servidores totalmente gratuitos.

Qualquer coisa pode me mandar uma mensagem no meu contato pessoal que irei responder:

[Silas Rodrigues - WhatsApp](https://wa.me/5519992576970)
