### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [SilasRodrigues19/NLW-IA#6]
SILAS MY FRIEND UNFORTUNATELY I DONT SPEAK PORTUGUESE...TELL ME PLEASE HOW IT WORKS BECAUSE I TRY AND NOTHING!AND SOMETHING MORE...HOW MANY MB I CAN UPLOAD?

**Comment by SilasRodrigues19** [comment]
Hey @KENPOKASMMA1982 

You need to select the video and click on the `Upload video` button and wait for the entire process to be completed, the button will be emerald in color and with the text `Done` when everything is ok. After that, you select an existing prompt or pass the instructions manually to the textarea and finally click on `Execute`

The application is currently configured to allow up to `25MB.`

If in doubt, you can click on the `Help` button in the header and explain the application flow.

See this demo below:


https://github.com/SilasRodrigues19/NLW-IA/assets/47532703/d1f4ecae-74eb-4757-aa97-14ffa51bcbef

**Comment by KENPOKASMMA1982** [comment]
WOWWWWWW..........PLEASEEEEEEEEEEEE COULD YOU MAKE IT ALLOW MORE THAN 100-200 MB?WHAT YOU THINK MY FRIEND?

**Comment by SilasRodrigues19** [comment]
Processing becomes very slow if the application allows 100 MB or more during upload, the idea is to transcribe only small videos even with a maximum of 25 MB. You can follow the README documentation and run locally on your machine.

Here are the instructions:

[Instructions for running the project's front end on your machine](https://github.com/SilasRodrigues19/NLW-IA/blob/main/README.md#installation)
[Instructions for running the project's back end on your machine](https://github.com/SilasRodrigues19/NLW-IA-API/blob/main/README.md#installation)

In the backend, open the [`upload-videos.ts`](https://github.com/SilasRodrigues19/NLW-IA-API/blob/e6ec25f7cb6df969bcd8a2a07df518cf5d409ce4/src/routes/upload-videos.ts#L16) file, you need to change the value from 25 to 100, then it will allow 100 MB. It should look like this:

```ts
// src/routes/upload-videos.ts

export async function uploadVideoRoute(app: FastifyInstance) {

  app.register(fastifyMultipart, {
    limits: {
      fileSize: 1_048_576 * 100, // 100MB
    }
  });
  // ...
}


```

**Comment by KENPOKASMMA1982** [comment]
Microsoft Windows [Version 10.0.19045.3448]
(c) Microsoft Corporation. Με επιφύλαξη κάθε νόμιμου δικαιώματος.

C:\Users\User\Downloads\NLW-IA-main\NLW-IA-main>pnpm install
'pnpm' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\User\Downloads\NLW-IA-main\NLW-IA-main>npm i
C:\Users\User\AppData\Roaming\npm\node_modules\npm\lib\es6\validate-engines.js:31
    throw err
    ^

Error: Cannot find module 'timers/promises'
Require stack:
- C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\agent\lib\util.js
- C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\agent\lib\index.js
- C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\make-fetch-happen\lib\remote.js
- C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\make-fetch-happen\lib\cache\entry.js
- C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\make-fetch-happen\lib\cache\index.js
- C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\make-fetch-happen\lib\fetch.js
- C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\make-fetch-happen\lib\index.js
- C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-fetch\lib\index.js
- C:\Users\User\AppData\Roaming\npm\node_modules\npm\lib\utils\replace-info.js
- C:\Users\User\AppData\Roaming\npm\node_modules\npm\lib\utils\error-message.js
- C:\Users\User\AppData\Roaming\npm\node_modules\npm\lib\utils\exit-handler.js
- C:\Users\User\AppData\Roaming\npm\node_modules\npm\lib\cli-entry.js
- C:\Users\User\AppData\Roaming\npm\node_modules\npm\lib\cli.js
- C:\Users\User\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\agent\lib\util.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\@npmcli\\agent\\lib\\util.js',
    'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\@npmcli\\agent\\lib\\index.js',
    'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\make-fetch-happen\\lib\\remote.js',
    'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\make-fetch-happen\\lib\\cache\\entry.js',
    'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\make-fetch-happen\\lib\\cache\\index.js',
    'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\make-fetch-happen\\lib\\fetch.js',
    'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\make-fetch-happen\\lib\\index.js',
    'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\npm-registry-fetch\\lib\\index.js',
    'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\lib\\utils\\replace-info.js',
    'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\lib\\utils\\error-message.js',
    'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\lib\\utils\\exit-handler.js',
    'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\lib\\cli-entry.js',
    'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\lib\\cli.js',
    'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js'
  ]
}

C:\Users\User\Downloads\NLW-IA-main\NLW-IA-main>npm run dev
C:\Users\User\AppData\Roaming\npm\node_modules\npm\lib\es6\validate-engines.js:31
    throw err
    ^

Error: Cannot find module 'timers/promises'
Require stack:
- C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\agent\lib\util.js
- C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\agent\lib\index.js
- C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\make-fetch-happen\lib\remote.js
- C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\make-fetch-happen\lib\cache\entry.js
- C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\make-fetch-happen\lib\cache\index.js
- C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\make-fetch-happen\lib\fetch.js
- C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\make-fetch-happen\lib\index.js
- C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-fetch\lib\index.js
- C:\Users\User\AppData\Roaming\npm\node_modules\npm\lib\utils\replace-info.js
- C:\Users\User\AppData\Roaming\npm\node_modules\npm\lib\utils\error-message.js
- C:\Users\User\AppData\Roaming\npm\node_modules\npm\lib\utils\exit-handler.js
- C:\Users\User\AppData\Roaming\npm\node_modules\npm\lib\cli-entry.js
- C:\Users\User\AppData\Roaming\npm\node_modules\npm\lib\cli.js
- C:\Users\User\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\agent\lib\util.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\@npmcli\\agent\\lib\\util.js',
    'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\@npmcli\\agent\\lib\\index.js',
    'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\make-fetch-happen\\lib\\remote.js',
    'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\make-fetch-happen\\lib\\cache\\entry.js',
    'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\make-fetch-happen\\lib\\cache\\index.js',
    'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\make-fetch-happen\\lib\\fetch.js',
    'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\make-fetch-happen\\lib\\index.js',
    'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\npm-registry-fetch\\lib\\index.js',
    'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\lib\\utils\\replace-info.js',
    'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\lib\\utils\\error-message.js',
    'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\lib\\utils\\exit-handler.js',
    'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\lib\\cli-entry.js',
    'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\lib\\cli.js',
    'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js'
  ]
}

C:\Users\User\Downloads\NLW-IA-main\NLW-IA-main>

**Comment by SilasRodrigues19** [comment]
Install the NodeJS in the following link:

https://nodejs.org/dist/v18.18.0/node-v18.18.0-x64.msi

And then, install `pnpm` in the terminal with `npm`

```sh
npm i -g pnpm
```

**Comment by SilasRodrigues19** [comment]
> Install the NodeJS in the following link:
> 
> https://nodejs.org/dist/v18.18.0/node-v18.18.0-x64.msi
> 
> And then, install `pnpm` in the terminal with `npm`
> 
> ```shell
> npm i -g pnpm
> ```

For other errors that arise, you will need to consult the README project and follow the step by step instructions. I won't be able to help at the moment due to other priorities.
